Repository UMC-with-you/WithYouServer, pull requests merged in 2024-01, with the labels that each got.

#4 [Refactor] 프로젝트 패키지 구조 정의
  build.gradle
  src/main/java/UMC/WithYou/WithYouApplication.java
  src/main/java/UMC/WithYou/common/config/SwaggerConfig.java
  src/main/java/UMC/WithYou/common/validation/annotation/TestAnnotation.java
  src/main/java/UMC/WithYou/common/validation/validator/TestValidator.java
  src/main/java/UMC/WithYou/controller/RewindController.java
  src/main/java/UMC/WithYou/converter/RewindConverter.java
  src/main/java/UMC/WithYou/domain/BaseEntity.java
  src/main/java/UMC/WithYou/domain/rewind/Mood.java
  src/main/java/UMC/WithYou/domain/rewind/Rewind.java
  src/main/java/UMC/WithYou/domain/rewind/RewindQna.java
  src/main/java/UMC/WithYou/domain/rewind/RewindQuestion.java
  src/main/java/UMC/WithYou/dto/RewindRequest.java
  src/main/java/UMC/WithYou/dto/RewindResponse.java
  src/main/java/UMC/WithYou/member/domain/member.java
  src/main/java/UMC/WithYou/repository/rewind/RewindQnaRepository.java
  src/main/java/UMC/WithYou/repository/rewind/RewindQuestionRepository.java
  src/main/java/UMC/WithYou/repository/rewind/RewindRepository.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandService.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/rewind/RewindQueryService.java
  src/main/java/UMC/WithYou/service/rewind/RewindQueryServiceImpl.java
  src/main/resources/data.sql
Labels: 🛠️refactoring, 🏗️chore

#11 [Feat]#10 PackingItem 관련 클래스 정의
  src/main/java/UMC/WithYou/controller/PackingItemController.java
  src/main/java/UMC/WithYou/domain/PackingItem.java
  src/main/java/UMC/WithYou/repository/PackingItemRepository.java
  src/main/java/UMC/WithYou/service/PackingItemService.java
Labels: ✨feature

#9 [Feat]#8 Post 관련 클래스 정의
  src/main/java/UMC/WithYou/controller/PostController.java
  src/main/java/UMC/WithYou/converter/PostConverter.java
  src/main/java/UMC/WithYou/domain/Post/Comment.java
  src/main/java/UMC/WithYou/domain/Post/Post.java
  src/main/java/UMC/WithYou/domain/Post/PostMedia.java
  src/main/java/UMC/WithYou/domain/Post/Reply.java
  src/main/java/UMC/WithYou/domain/Post/ScrapedPost.java
  src/main/java/UMC/WithYou/repository/post/CommentRepository.java
  src/main/java/UMC/WithYou/repository/post/PostRepository.java
  src/main/java/UMC/WithYou/repository/post/ReplyRepository.java
  src/main/java/UMC/WithYou/service/post/CommentService.java
  src/main/java/UMC/WithYou/service/post/PostService.java
  src/main/java/UMC/WithYou/service/post/ReplyService.java
Labels: ✨feature

#14 [FEAT] REWIND 작성 기능 구현
  build.gradle
  src/main/java/UMC/WithYou/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC/WithYou/common/config/SwaggerConfig.java
  src/main/java/UMC/WithYou/common/validation/annotation/ExistQuestionId.java
  src/main/java/UMC/WithYou/common/validation/validator/ExistQuestionIdValidator.java
  src/main/java/UMC/WithYou/controller/RewindController.java
  src/main/java/UMC/WithYou/converter/RewindConverter.java
  src/main/java/UMC/WithYou/domain/rewind/Rewind.java
  src/main/java/UMC/WithYou/domain/rewind/RewindQna.java
  src/main/java/UMC/WithYou/dto/RewindRequest.java
  src/main/java/UMC/WithYou/dto/RewindResponse.java
  src/main/java/UMC/WithYou/repository/rewind/RewindQnaRepository.java
  src/main/java/UMC/WithYou/repository/rewind/RewindQuestionRepository.java
  src/main/java/UMC/WithYou/repository/rewind/RewindRepository.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandService.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/rewind/RewindQuestionQueryService.java
  src/main/java/UMC/WithYou/service/rewind/RewindQuestionQueryServiceImpl.java
Labels: ✨feature, 🛠️refactoring

#15 [Feat]#2 Notice 및 NoticeCheck 작성 기능 구현
  .gitignore
  build.gradle
  src/main/java/UMC/WithYou/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC/WithYou/common/validation/annotation/ExistNotices.java
  src/main/java/UMC/WithYou/common/validation/validator/NoticesExistValidator.java
  src/main/java/UMC/WithYou/controller/NoticeCheckController.java
  src/main/java/UMC/WithYou/controller/NoticeController.java
  src/main/java/UMC/WithYou/converter/NoticeCheckConverter.java
  src/main/java/UMC/WithYou/converter/NoticeConverter.java
  src/main/java/UMC/WithYou/domain/notice/Notice.java
  src/main/java/UMC/WithYou/domain/notice/NoticeCheck.java
  src/main/java/UMC/WithYou/dto/NoticeCheckResponseDTO.java
  src/main/java/UMC/WithYou/dto/NoticeRequestDTO.java
  src/main/java/UMC/WithYou/dto/NoticeResponseDTO.java
  src/main/java/UMC/WithYou/repository/notice/NoticeCheckRepository.java
  src/main/java/UMC/WithYou/repository/notice/NoticeRepository.java
  src/main/java/UMC/WithYou/repository/notice/NoticeRepositoryCustom.java
  src/main/java/UMC/WithYou/repository/notice/NoticeRepositoryCustomImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCheckCommandService.java
  src/main/java/UMC/WithYou/service/notice/NoticeCheckCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandService.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandServiceImpl.java
Labels: ✨feature

#28 [REFACTOR]# Update application-dev.yml
  src/main/resources/application-dev.yml
Labels: 🛠️refactoring

#40 Feat/#39 travel
  src/main/java/UMC/WithYou/controller/PackingItemController.java
  src/main/java/UMC/WithYou/controller/PostController.java
  src/main/java/UMC/WithYou/controller/RewindController.java
  src/main/java/UMC/WithYou/controller/TravelController.java
  src/main/java/UMC/WithYou/domain/PackingItem.java
  src/main/java/UMC/WithYou/domain/Post/Post.java
  src/main/java/UMC/WithYou/domain/dummy/DummyTravel.java
  src/main/java/UMC/WithYou/domain/member/Member.java
  src/main/java/UMC/WithYou/domain/travel/Travel.java
  src/main/java/UMC/WithYou/domain/travel/TravelStatus.java
  src/main/java/UMC/WithYou/domain/travel/Traveler.java
  src/main/java/UMC/WithYou/dto/TravelRequestDTO.java
  src/main/java/UMC/WithYou/dto/TravelResponseDTO.java
  src/main/java/UMC/WithYou/repository/TravelRepository.java
  src/main/java/UMC/WithYou/repository/dummy/DummyTravelRepository.java
  src/main/java/UMC/WithYou/service/PackingItemService.java
  src/main/java/UMC/WithYou/service/TravelService.java
  src/main/java/UMC/WithYou/service/post/PostService.java
Labels: ✨feature, 🛠️refactoring

#42 [Feat] security
  .DS_Store
  src/main/java/UMC/WithYou/common/config/AuthConfig.java
  src/main/java/UMC/WithYou/controller/AuthController.java
Labels: ✨feature
