Repository UMC-with-you/WithYouServer, pull requests merged in 2024-02, with the labels that each got.

#49 [REFACTOR]#22 Notice 및 NoticeCheck 리펙토링
  src/main/java/UMC/WithYou/controller/NoticeCheckController.java
  src/main/java/UMC/WithYou/converter/NoticeCheckConverter.java
  src/main/java/UMC/WithYou/converter/NoticeConverter.java
  src/main/java/UMC/WithYou/domain/notice/Notice.java
  src/main/java/UMC/WithYou/dto/NoticeCheckResponseDTO.java
  src/main/java/UMC/WithYou/repository/notice/NoticeCheckRepository.java
  src/main/java/UMC/WithYou/repository/notice/NoticeRepository.java
  src/main/java/UMC/WithYou/repository/notice/NoticeRepositoryCustomImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCheckCommandService.java
  src/main/java/UMC/WithYou/service/notice/NoticeCheckCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandServiceImpl.java
Labels: 🛠️refactoring

#46 [Feat] jasypt
  build.gradle
  src/main/java/UMC/WithYou/common/config/JasyptConfig.java
Labels: ✨feature

#56 [FEAT] Create CD.yml
  .github/workflows/Backend-CD.yml
  .github/workflows/Backend-CI.yml
  src/main/java/UMC/WithYou/controller/TravelController.java
  src/main/java/UMC/WithYou/service/TravelService.java
Labels: ✨feature

#57 [FIX] Cd가 Ci보다 먼저 트리거 되어 끝나는 문제 수정
  .github/workflows/Backend-CD.yml
  .github/workflows/Backend-CI.yml
Labels: ✨feature

#58 [FIX]#55 Cd가 Ci보다 먼저 트리거 되어 끝나는 문제 수정
  .github/workflows/Backend-CD.yml
Labels: 🐞bug

#60 [Feat] google login
  src/main/java/UMC/WithYou/controller/AuthController.java
  src/main/java/UMC/WithYou/domain/auth/GoogleUserInfo.java
  src/main/java/UMC/WithYou/domain/auth/KakaoUserInfo.java
  src/main/java/UMC/WithYou/service/auth/OAuth2ProviderService.java
Labels: ✨feature

#64 [REFACTOR]#64 Member 어노테이션 이름 변경 및 적용
  src/main/java/UMC/WithYou/common/annotation/AuthorizedMember.java
  src/main/java/UMC/WithYou/common/resolver/MemberArgumentResolver.java
  src/main/java/UMC/WithYou/controller/CommentController.java
  src/main/java/UMC/WithYou/controller/PostController.java
  src/main/java/UMC/WithYou/controller/ReplyController.java
  src/main/java/UMC/WithYou/controller/TravelController.java
  src/main/java/UMC/WithYou/domain/Post/Post.java
  src/main/java/UMC/WithYou/domain/Post/PostMedia.java
  src/main/java/UMC/WithYou/domain/Post/ScrapedPost.java
  src/main/java/UMC/WithYou/domain/member/Member.java
  src/main/java/UMC/WithYou/domain/travel/Travel.java
  src/main/java/UMC/WithYou/domain/travel/Traveler.java
  src/main/java/UMC/WithYou/dto/TravelResponseDTO.java
  src/main/java/UMC/WithYou/service/TravelService.java
  src/main/java/UMC/WithYou/service/post/CommentService.java
  src/main/java/UMC/WithYou/service/post/PostService.java
  src/main/java/UMC/WithYou/service/post/ReplyService.java
Labels: 🛠️refactoring

#65 [Refactor] REWIND API 로직 수정
  src/main/java/UMC/WithYou/common/annotation/AuthorizedMember.java
  src/main/java/UMC/WithYou/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC/WithYou/common/resolver/MemberArgumentResolver.java
  src/main/java/UMC/WithYou/controller/RewindController.java
  src/main/java/UMC/WithYou/domain/rewind/Rewind.java
  src/main/java/UMC/WithYou/domain/travel/Travel.java
  src/main/java/UMC/WithYou/repository/rewind/RewindRepository.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandService.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/rewind/RewindQueryService.java
  src/main/java/UMC/WithYou/service/rewind/RewindQueryServiceImpl.java
Labels: 🛠️refactoring

#66 [REFACTOR]#63 refactor Rewind's swagger documentation
  src/main/java/UMC/WithYou/controller/RewindController.java
Labels: 🛠️refactoring

#62 [FEAT]#21 Cloud 생성 및 조회
  .DS_Store
  build.gradle
  src/main/java/UMC/WithYou/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC/WithYou/common/config/AppConfig.java
  src/main/java/UMC/WithYou/common/config/S3Config.java
  src/main/java/UMC/WithYou/controller/CloudController.java
  src/main/java/UMC/WithYou/controller/NoticeCheckController.java
  src/main/java/UMC/WithYou/controller/NoticeController.java
  src/main/java/UMC/WithYou/converter/CloudConverter.java
  src/main/java/UMC/WithYou/converter/NoticeCheckConverter.java
  src/main/java/UMC/WithYou/converter/NoticeConverter.java
  src/main/java/UMC/WithYou/domain/cloud/Cloud.java
  src/main/java/UMC/WithYou/domain/cloud/CloudMedia.java
  src/main/java/UMC/WithYou/domain/notice/NoticeCheck.java
  src/main/java/UMC/WithYou/dto/cloud/CloudRequestDTO.java
  src/main/java/UMC/WithYou/dto/cloud/CloudResponseDTO.java
  src/main/java/UMC/WithYou/dto/notice/NoticeCheckResponseDTO.java
  src/main/java/UMC/WithYou/dto/notice/NoticeRequestDTO.java
  src/main/java/UMC/WithYou/dto/notice/NoticeResponseDTO.java
  src/main/java/UMC/WithYou/repository/cloud/CloudCustomRepository.java
  src/main/java/UMC/WithYou/repository/cloud/CloudCustomRepositoryImpl.java
  src/main/java/UMC/WithYou/repository/cloud/CloudMediaRepository.java
  src/main/java/UMC/WithYou/repository/cloud/CloudRepository.java
  src/main/java/UMC/WithYou/service/S3Service.java
  src/main/java/UMC/WithYou/service/cloud/CloudService.java
  src/main/java/UMC/WithYou/service/cloud/CloudServiceImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCheckCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandService.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandServiceImpl.java
  src/main/java/UMC/WithYou/support/AuthFilter.java
  src/main/resources/application.yml
Labels: ✨feature

#69 [Fix] S3 관련 암호화
  src/main/resources/application.yml
Labels: 🐞bug

#72 [FIX]#71 fix logic travel log deletion
  src/main/java/UMC/WithYou/service/TravelService.java
Labels: 🛠️refactoring

#70 [REFACTOR]#63 refactor data.sql script
  src/main/java/UMC/WithYou/converter/RewindConverter.java
  src/main/java/UMC/WithYou/dto/rewind/RewindRequest.java
  src/main/java/UMC/WithYou/service/rewind/RewindCommandServiceImpl.java
  src/main/java/UMC/WithYou/service/rewind/RewindQueryServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
Labels: 🛠️refactoring

#78 @AuthorizedMember 어노테이션이 붙은 컨트롤러 Swagger 정리
  src/main/java/UMC/WithYou/controller/CommentController.java
  src/main/java/UMC/WithYou/controller/PostController.java
  src/main/java/UMC/WithYou/controller/ReplyController.java
  src/main/java/UMC/WithYou/controller/TravelController.java
Labels: 🛠️refactoring

#73 [refactor] notice 조회 DTO 수정
  src/main/java/UMC/WithYou/converter/NoticeConverter.java
  src/main/java/UMC/WithYou/dto/notice/NoticeCheckResponseDTO.java
Labels: 🛠️refactoring

#81 [Feat] apple login
  src/main/java/UMC/WithYou/common/config/AuthConfig.java
  src/main/java/UMC/WithYou/controller/AuthController.java
  src/main/java/UMC/WithYou/domain/auth/AppleUserInfo.java
  src/main/java/UMC/WithYou/domain/auth/GoogleUserInfo.java
  src/main/java/UMC/WithYou/domain/auth/KakaoUserInfo.java
  src/main/java/UMC/WithYou/domain/auth/UserInfo.java
  src/main/java/UMC/WithYou/domain/member/Identifier.java
  src/main/java/UMC/WithYou/domain/member/Member.java
  src/main/java/UMC/WithYou/dto/auth/ApplePublicKeyResponse.java
  src/main/java/UMC/WithYou/repository/member/MemberRepository.java
  src/main/java/UMC/WithYou/service/auth/AuthService.java
  src/main/java/UMC/WithYou/service/auth/OAuth2ProviderService.java
Labels: 🏗️chore

#85 [FIX] Data.sql 수정
  src/main/java/UMC/WithYou/WithYouApplication.java
  src/main/java/UMC/WithYou/repository/member/MemberRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
Labels: 🐞bug

#86 [REFACTOR] MemberAnotation
  src/main/java/UMC/WithYou/common/annotation/AuthorizedMember.java
  src/main/java/UMC/WithYou/common/config/AppConfig.java
  src/main/java/UMC/WithYou/common/resolver/MemberArgumentResolver.java
  src/main/java/UMC/WithYou/domain/auth/UserPrincipal.java
Labels: 🛠️refactoring

#87 [REFACTOR] MemberAnnotation
  src/main/java/UMC/WithYou/service/auth/UserDetailsServiceImpl.java
Labels: 🏗️chore

#90 [FEAT] Create MemberArgumentResolver.Class
  src/main/java/UMC/WithYou/common/annotation/AuthorizedMember.java
  src/main/java/UMC/WithYou/common/config/AppConfig.java
  src/main/java/UMC/WithYou/common/resolver/MemberArgumentResolver.java
Labels: ✨feature

#95 [Feat]#21 cloud 삭제 기능
  src/main/java/UMC/WithYou/common/apiPayload/code/status/ErrorStatus.java
  src/main/java/UMC/WithYou/common/validation/annotation/ExistClouds.java
  src/main/java/UMC/WithYou/common/validation/validator/CloudsExistValidator.java
  src/main/java/UMC/WithYou/controller/CloudController.java
  src/main/java/UMC/WithYou/converter/CloudConverter.java
  src/main/java/UMC/WithYou/domain/cloud/CloudMedia.java
  src/main/java/UMC/WithYou/dto/cloud/CloudRequestDTO.java
  src/main/java/UMC/WithYou/service/cloud/CloudService.java
  src/main/java/UMC/WithYou/service/cloud/CloudServiceImpl.java
Labels: ✨feature

#97 [Refactor]#21 컨트롤러 어노테이션 수정
  src/main/java/UMC/WithYou/controller/CloudController.java
Labels: 🛠️refactoring

#98 [Fix]#21: List<MultipartFile>을 MultipartFile로 수정
  src/main/java/UMC/WithYou/controller/CloudController.java
  src/main/java/UMC/WithYou/converter/CloudConverter.java
  src/main/java/UMC/WithYou/domain/cloud/CloudMedia.java
  src/main/java/UMC/WithYou/service/S3Service.java
  src/main/java/UMC/WithYou/service/cloud/CloudService.java
  src/main/java/UMC/WithYou/service/cloud/CloudServiceImpl.java
Labels: 🛠️refactoring

#100 [FIX]#99 modify addTravelMember method not to add member twice
  src/main/java/UMC/WithYou/domain/travel/Travel.java
Labels: 🐞bug

#103 [Fix]#21: 어노테이션 수정
  src/main/java/UMC/WithYou/controller/CloudController.java
Labels: 🛠️refactoring

#104 [TEST] 연동테스트
  src/main/java/UMC/WithYou/controller/CloudController.java
  src/main/java/UMC/WithYou/dto/cloud/CloudRequestDTO.java
Labels: 🧪test

#107 [Test]#21 연동관련 수정사항
  src/main/java/UMC/WithYou/controller/CloudController.java
Labels: 🧪test

#109 [Refactor]#21 List<MultipartFile>로 변경
  src/main/java/UMC/WithYou/controller/CloudController.java
  src/main/java/UMC/WithYou/service/cloud/CloudService.java
  src/main/java/UMC/WithYou/service/cloud/CloudServiceImpl.java
  src/main/java/UMC/WithYou/service/notice/NoticeCommandServiceImpl.java
Labels: 🛠️refactoring

#94 [Feat] apple login
  src/main/java/UMC/WithYou/dto/auth/LoginRequest.java
  src/main/java/UMC/WithYou/service/auth/AppleTokenVerifier.java
  src/main/java/UMC/WithYou/service/auth/OAuth2ProviderService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: ✨feature

#108 Feat/#105 member
  src/main/java/UMC/WithYou/controller/AuthController.java
  src/main/java/UMC/WithYou/controller/MemberController.java
  src/main/java/UMC/WithYou/domain/member/Member.java
  src/main/java/UMC/WithYou/dto/auth/LoginRequest.java
  src/main/java/UMC/WithYou/dto/member/NameRequest.java
  src/main/java/UMC/WithYou/service/auth/AuthService.java
  src/main/java/UMC/WithYou/service/member/MemberService.java
Labels: ✨feature

#110 [FEAT] 사용자 정보 조회 API
  src/main/java/UMC/WithYou/controller/MemberController.java
  src/main/java/UMC/WithYou/dto/auth/MemberResponse.java
  src/main/java/UMC/WithYou/service/member/MemberService.java
Labels: ✨feature
